apiVersion: apps/v1
kind: CronWorkflow
metadata:
  name: hello-python
spec:
  schedule: "*/5 * * * *"
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      # modify the following line with your Docker Hub account name
      - image: index.docker.io/zahirbasha/argocd:hellopythontag
        name: hello-python
        ports:
        - containerPort: 8082
