
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-python
  namespace: project2
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: index.docker.io/zahirbasha/demo:hellopython
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
